//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pigeon
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdresatDW
    {
        public int Id { get; set; }
        public int WiadomośćId { get; set; }
    
        public virtual Kontakt Kontakt { get; set; }
        public virtual Wiadomość Wiadomość { get; set; }
    }
}
