//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pigeon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int Id { get; set; }
        public TypAdresu Typ { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public string KodPocztowy { get; set; }
        public string NrDomu { get; set; }
        public Nullable<Wojewodztwo> Wojewodztwo { get; set; }
        public string Kraj { get; set; }
        public string NrLokalu { get; set; }
        public int PodmiotId1 { get; set; }
    
        public virtual Podmiot Podmiot { get; set; }
    }
}
