//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pigeon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakt
    {
        public int Id { get; set; }
        public string Wartość { get; set; }
        private int PodmiotId { get; set; }
    
        public virtual Podmiot Podmiot { get; set; }
        public virtual DefKontaktu DefKontaktu { get; set; }
    }
}
