//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pigeon
{
    using System;
    
    public enum TypAdresu : int
    {
        Zamieszkania = 0,
        Zameldowania = 1,
        DoKorespondencji = 2
    }
}
