//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pigeon
{
    using System;
    
    public enum TypKontaktu : int
    {
        Tel_Stacjonarny_Prywatny = 0,
        Tel_Stasjonarny_Służbowy = 1,
        Tel_Komórkowy_Prywatny = 2,
        Tel_Komórkowy_Służbowy = 3,
        Email_Prywatny = 4,
        Email_Służbowy = 5
    }
}
