//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pigeon
{
    using System;
    
    public enum TypPrzypomnienia : int
    {
        Minuty = 0,
        Godziny = 1,
        Dni = 2,
        Tygodnie = 3
    }
}
