//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pigeon
{
    using System;
    
    public enum Wojewodztwo : int
    {
        Dolnośląskie = 0,
        KujawskoPomorskie = 1,
        Lubelskie = 2,
        Lubuskie = 3,
        Łódzkie = 4,
        Małopolskie = 5,
        Mazowieckie = 6,
        Opolskie = 7,
        Podkarpackie = 8,
        Podlaskie = 9,
        Pomorskie = 10,
        Śląskie = 11,
        Świętokrzyskie = 12,
        WarmińskoMazurskie = 13,
        Wielkopolskie = 14,
        Zachodniopomorskie = 15
    }
}
