//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pigeon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zadanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zadanie()
        {
            this.IsNotificate = false;
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public System.DateTime Data { get; set; }
        public TypPrzypomnienia Przypomnienie { get; set; }
        public int Wyprzedzenie { get; set; }
        public bool IsNotificate { get; set; }
    
        public virtual Podmiot Podmiot { get; set; }
    }
}
